### ISSUE TITLE
Are ya coding son?

### ISSUE THREAD

**Issue by protonesso** [rmon-vfer/yandereSimulatorSource#13]

**Comment by starmlerp** [comment]
n-no! dad, I'm just studying bible! on my computer. You know, modern stuff

**Comment by m1ch4ll064** [comment]
ARE YA CODING SON?

**Comment by starmlerp** [comment]
Dad, no! It's not what it looks like!

**Comment by starmlerp** [comment]
AAAAAAAAAAAAA-
