### ISSUE TITLE
Holy shit dude...

### ISSUE THREAD

**Issue by Alexdatadestroyer** [rmon-vfer/yandereSimulatorSource#2]
https://github.com/rmon-vfer/yandereSimulatorSource/blob/1fa8c3a286ae4daac15f702917fc2471a87d0e75/Assembly-CSharp/StudentScript.cs#L1127

**Comment by alula** [comment]
I suppose it was rather a compiler optimization on constant expression, I'd have to look at the bytecode for more information (if any)
