### ISSUE TITLE
How do I add more else if statements?

### ISSUE THREAD

**Issue by LargeDev** [rmon-vfer/yandereSimulatorSource#8]
There seems to be way to little else if statements... Where do you think you could incorporate more to make the coding process much more efficient and easier to sort through pre-existing code?

**Comment by Sheinxy** [comment]
Just look out for any switch statements you can find, and replace them with as many if-else statements as possible. Switch statements are slower than else-if statements

You can also make sure to check that a boolean is either true or false when checking one, like
if (test == true) 
{
    // Some code
}
else if (test == false)
{
    // Some other code
}
This will make sure that your boolean is indeed either true or false whilst increasing the efficiency of the program

**Comment by LargeDev** [comment]
> Just look out for any switch statements you can find, and replace them with as many if-else statements as possible. Switch statements are slower than else-if statements
> 
> You can also make sure to check that a boolean is either true or false when checking one, like
> if (test == true)
> {
> // Some code
> }
> else if (test == false)
> {
> // Some other code
> }
> This will make sure that your boolean is indeed either true or false whilst increasing the efficiency of the program

Yeah, I heard those dang pesky switch statements caused too much lag, good on yandev for incorporating just the right amount of else if statements.
